spring:
  profiles: local

aws:
  region: us-east-1
  sqs:
    queue-name: products-queue
    # Optional endpoint for LocalStack testing. Comment out in AWS environment
    endpoint: http://localhost:4566

# Example datasource if used by project
# spring:
#   datasource:
#     url: jdbc:h2:mem:products;DB_CLOSE_DELAY=-1
#     username: sa
#     password:
